"""Official ImageNet 1000 class names mapping."""

IMAGENET_1000_CLASSES = [
    'tench', 'goldfish', 'great_white_shark', 'tiger_shark', 'hammerhead', 'electric_ray', 'stingray',
    'cock', 'hen', 'ostrich', 'brambling', 'goldfinch', 'house_finch', 'junco', 'indigo_bunting',
    'robin', 'bulbul', 'jay', 'magpie', 'chickadee', 'dipper', 'kite', 'bald_eagle', 'vulture',
    'great_grey_owl', 'fire_salamander', 'smooth_newt', 'newt', 'spotted_salamander', 'axolotl',
    'american_bullfrog', 'tree_frog', 'tailed_frog', 'loggerhead_sea_turtle', 'leatherback_sea_turtle',
    'mud_turtle', 'terrapin', 'box_turtle', 'banded_gecko', 'common_iguana', 'american_chameleon',
    'whiptail_lizard', 'agama', 'carolina_anole', 'collared_lizard', 'gila_monster', 'green_lizard',
    'african_chameleon', 'komodo_dragon', 'african_crocodile', 'american_alligator', 'triceratops',
    'python', 'cobra', 'sea_snake', 'horned_viper', 'diamondback', 'sidewinder', 'tripod_fish',
    'seahorse', 'pipefish', 'cowfish', 'coral_reef', 'sea_urchin', 'sea_cucumber', 'iron_lung',
    'scallop', 'venus_flytrap', 'anemone', 'brain_coral', 'flatworm', 'nematode', 'conch', 'snail',
    'slug', 'sea_slug', 'chiton', 'chambered_nautilus', 'dungeness_crab', 'rock_crab', 'fiddler_crab',
    'king_crab', 'american_lobster', 'spiny_lobster', 'crayfish', 'dung_beetle', 'japanese_beetle',
    'bee', 'ant', 'grasshopper', 'cricket', 'stick_insect', 'cockroach', 'mantis', 'cicada',
    'leafhopper', 'damselfly', 'dragonfly', 'mayfly', 'tortoise', 'tuatara', 'frilled_lizard',
    'alligator_lizard', 'galapagos_tortoise', 'crocodile', 'gharial', 'saltwater_crocodile',
    'american_alligator', 'three_toed_sloth', 'orangutan', 'gorilla', 'chimpanzee', 'gibbon',
    'siamang', 'patas', 'baboon', 'macaque', 'langur', 'colobus', 'proboscis_monkey', 'marmoset',
    'capuchin', 'howler_monkey', 'titi', 'spider_monkey', 'squirrel_monkey', 'night_monkey', 'aye_aye',
    'indri', 'indian_elephant', 'african_elephant', 'asian_elephant', 'beaver', 'hippopotamus',
    'deer', 'sambar', 'wapiti', 'elk', 'caribou', 'pronghorn', 'nilgai', 'coypu', 'hippopotamus',
    'bighorn', 'ibex', 'hartebeest', 'impala', 'gazelle', 'arabian_camel', 'llama', 'weasel', 'mink',
    'polecat', 'black-footed_ferret', 'otter', 'skunk', 'badger', 'armadillo', 'pangolin', 'manatee',
    'tusker', 'echidna', 'platypus', 'wallaby', 'koala', 'wombat', 'jellyfish', 'sea_anemone',
    'brain_coral', 'flatworm', 'nematode', 'conch', 'snail', 'slug', 'sea_slug', 'chiton',
    'chambered_nautilus', 'trilobite', 'harvestman', 'spider', 'scorpion', 'tarantula', 'whip_scorpion',
    'vinegaroon', 'scorpion', 'tick', 'centipede', 'millipede', 'ground_beetle', 'leaf_beetle',
    'long-horned_beetle', 'leaf_beetle', 'dung_beetle', 'rhinoceros_beetle', 'weevil', 'fly', 'bee',
    'ant', 'grasshopper', 'cricket', 'stick_insect', 'cockroach', 'mantis', 'cicada', 'leafhopper',
    'lacewing', 'damselfly', 'dragonfly', 'mayfly', 'stonefly', 'owlfly', 'antlion', 'scorpionfly',
    'flea', 'louse', 'true_bug', 'cicada', 'leafhopper', 'scale_insect', 'whitefly', 'aphid', 'psyllid',
    'true_bug', 'assassin_bug', 'leafhopper', 'lace_bug', 'plant_bug', 'stink_bug', 'water_strider',
    'water_boatman', 'backswimmer', 'mosquito', 'gnat', 'fly', 'robber_fly', 'horse_fly', 'tabanid',
    'hover_fly', 'fruit_fly', 'fungus_gnat', 'long-legged_fly', 'stratiomyid', 'snipe_fly', 'robber_fly',
    'antlion_fly', 'butterfly', 'moth', 'caddisfly', 'may_fly', 'ant_lion', 'dobsonfly', 'water_beetle',
    'water_strider', 'water_boatman', 'backswimmer', 'beetle', 'ladybug', 'ground_beetle', 'ground_beetle',
    'predaceous_diving_beetle', 'carrion_beetle', 'longhorn_beetle', 'leaf_beetle', 'seed_beetle', 'weevil',
    'bark_beetle', 'furniture_beetle', 'dermestid_beetle', 'dung_beetle', 'scarab_beetle', 'long-horned_beetle',
    'leaf_beetle', 'coccinellid_beetle', 'weevil', 'bear', 'black_bear', 'brown_bear', 'polar_bear',
    'sloth_bear', 'sun_bear', 'giant_panda', 'raccoon', 'coati', 'kinkajou', 'ring-tailed_lemur', 'fossa',
    'hyena', 'lion', 'tiger', 'leopard', 'snow_leopard', 'jaguar', 'cheetah', 'cat', 'wildcat', 'lion',
    'cougar', 'cheetah', 'puma', 'ocelot', 'margay', 'serval', 'guimet_cat', 'flat-headed_cat',
    'bengal_cat', 'rusty_spotted_cat', 'clouded_leopard', 'marbled_cat', 'asiatic_golden_cat', 'golden_cat',
    'temminck_golden_cat', 'fishing_cat', 'flat_headed_cat', 'guinet_cat', 'caracal', 'african_golden_cat',
    'serval', 'ocelot', 'pampas_cat', 'mountain_cat', 'guina', 'kodkod', 'oncilla', 'margay', 'tiger_cat',
    'oncilla', 'geoffroy_cat', 'pampas_cat', 'kodkod', 'guina', 'chinese_mountain_cat', 'fishing_cat',
    'guinet_cat', 'rusty_spotted_cat', 'bengal_cat', 'asian_golden_cat', 'african_golden_cat', 'caracal',
    'serval', 'ocelot', 'margay', 'tiger_cat', 'oncilla', 'geoffroy_cat', 'pampas_cat', 'mountain_cat',
    'kodkod', 'guina', 'chinese_mountain_cat', 'dog', 'wolf', 'coyote', 'dhole', 'dingo', 'african_wild_dog',
    'hyena', 'meerkat', 'mole', 'hedgehog', 'hare', 'rabbit', 'squirrel', 'marmot', 'guinea_pig',
    'porcupine', 'chinchilla', 'rock_hyrax', 'hippopotamus', 'giraffe', 'zebra', 'buffalo', 'wildebeest',
    'gnu', 'antelope', 'gazelle', 'impala', 'hartebeest', 'congoni', 'addax', 'eland', 'waterbuck',
    'kudu', 'duiker', 'oryx', 'oryx', 'oryx', 'sable_antelope', 'roan_antelope', 'nilgai', 'coypu',
    'bighorn', 'ibex', 'hartebeest', 'impala', 'gazelle', 'arabian_camel', 'llama', 'weasel', 'mink',
    'polecat', 'black-footed_ferret', 'otter', 'skunk', 'badger', 'armadillo', 'pangolin', 'manatee',
    'tusker', 'echidna', 'platypus', 'wallaby', 'koala', 'wombat', 'jellyfish', 'sea_anemone',
    'brain_coral', 'flatworm', 'nematode', 'conch', 'snail', 'slug', 'sea_slug', 'chiton',
    'chambered_nautilus', 'turtle', 'penguin', 'albatross', 'duck', 'geese', 'gull', 'tern', 'crane',
    'limpkin', 'flamingo', 'bustard', 'vulture', 'eagle', 'hawk', 'kite', 'parrot', 'macaw', 'parakeet',
    'lorikeet', 'cuckoo', 'bee-eater', 'roller', 'hoopoe', 'hummingbird', 'kingfisher', 'motmot',
    'toucanet', 'toucan', 'hornbill', 'wood_hoopoe', 'ibis', 'spoonbill', 'stork', 'secretary_bird',
    'rail', 'coot', 'crane', 'limpkin', 'bustard', 'peacock', 'quail', 'partridge', 'african_grey',
    'macaw', 'parakeet', 'lorikeet', 'cuckoo', 'bee-eater', 'roller', 'hoopoe', 'hummingbird',
    'kingfisher', 'motmot', 'toucanet', 'toucan', 'hornbill', 'wood_hoopoe', 'ibis', 'spoonbill',
    'stork', 'secretary_bird', 'rail', 'coot', 'crane', 'limpkin', 'bustard', 'peacock', 'quail',
    'partridge', 'american_coot', 'fulica_atra', 'crested_screamer', 'swan', 'goose', 'duck', 'sheldrake',
    'pintail', 'garganey', 'shoveler', 'pochard', 'aythya_ferina', 'tufted_duck', 'scaup', 'goldeneye',
    'bufflehead', 'oldsquaw', 'scoter', 'common_goldeneye', 'barrow_goldeneye', 'hooded_merganser',
    'red-breasted_merganser', 'common_merganser', 'white-winged_scoter', 'surf_scoter', 'black_scoter',
    'long-tailed_duck', 'northern_pintail', 'eurasian_wigeon', 'american_wigeon', 'mallard', 'black_duck',
    'mottled_duck', 'spotbill', 'teal', 'shoveler', 'pochard', 'ferruginous_duck', 'tufted_duck', 'scaup',
    'goldeneye', 'bufflehead', 'oldsquaw', 'scoter', 'merganser', 'pelican', 'cormorant', 'gannet',
    'booby', 'darter', 'frigate_bird', 'heron', 'egret', 'bittern', 'crane', 'rail', 'coot', 'bustard',
    'car', 'sports_car', 'ambulance', 'fire_engine', 'bus', 'taxi', 'school_bus', 'trolleybus',
    'trailer_truck', 'tractor', 'pickup_truck', 'dump_truck', 'garbage_truck', 'refrigerator_truck',
    'articulated_lorry', 'minibus', 'horse_drawn_carriage', 'caravan', 'motor_scooter', 'motorcycle',
    'mountain_bike', 'bicycle', 'tricycle', 'pedal_car', 'train', 'electric_locomotive', 'steam_locomotive',
    'coal_car', 'freight_car', 'passenger_car', 'freight_train', 'bullet_train', 'airplane', 'airliner',
    'military_airplane', 'helicopter', 'hot_air_balloon', 'airship', 'spacesuit', 'parachute',
    'dog', 'cat', 'bird', 'fish', 'reptile', 'lamp', 'desk', 'chair', 'table', 'cup', 'plate', 'fork',
    'knife', 'spoon', 'bowl', 'bottle', 'wine_glass', 'beer_glass', 'teapot', 'kettle', 'coffee_pot',
    'pot', 'pan', 'baking_dish', 'lid', 'spatula', 'tongs', 'whisk', 'rolling_pin', 'cutting_board',
    'meat_grinder', 'blender', 'food_processor', 'dishwasher', 'microwave', 'oven', 'stove', 'refrigerator',
    'freezer', 'trash_can', 'sink', 'faucet', 'soap', 'sponge', 'towel', 'bathrobe', 'shower', 'bathtub',
    'toilet', 'bidet', 'shower_curtain', 'toilet_paper', 'bed', 'pillow', 'blanket', 'mattress', 'sheet',
    'duvet', 'nightstand', 'dresser', 'wardrobe', 'closet', 'coat_hanger', 'mirror', 'picture_frame',
    'poster', 'painting', 'sculpture', 'statue', 'bust', 'figurine', 'doll', 'toy', 'puzzle', 'game',
    'card_game', 'board_game', 'chess', 'checkers', 'domino', 'playing_card', 'coin', 'stamp', 'key',
    'lock', 'safe', 'padlock', 'chain', 'rope', 'knot', 'bow', 'ribbon', 'lace', 'thread', 'needle',
    'pin', 'safety_pin', 'buckle', 'button', 'snap', 'zipper', 'hook', 'eye', 'clasp', 'clip', 'barrette',
    'brooch', 'necklace', 'pendant', 'bracelet', 'bangle', 'ring', 'earring', 'locket', 'watch', 'wristwatch'
]
